# Generated by Django 3.1.4 on 2020-12-16 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('drone_reg', models.CharField(max_length=100)),
                ('weather', models.TextField(blank=True)),
                ('obstructions', models.TextField(blank=True)),
                ('takeoff_clear', models.BooleanField()),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preflights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('incidents', models.TextField(blank=True)),
                ('preflight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='dronelog.preflight')),
            ],
        ),
    ]
